name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard-mvp
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r integrations/qtickets_api/requirements.txt
          pip install pytest

      - name: Validate ClickHouse schema
        run: |
          python scripts/validate_clickhouse_schema.py

      - name: Run unit tests
        run: |
          pytest integrations/qtickets_api/tests -q

      - name: Build QTickets API image
        run: |
          docker build -f integrations/qtickets_api/Dockerfile .
